export { default as Dashboard} from "../pages/Dashboard";
export {default as MailSidebar} from "./MailSidebar"
export {default as Events} from "../pages/Events";
export {default as Files} from "../pages/Files";
export {default as Inbox} from "../pages/Mail/Inbox";
export {default as Email} from "../pages/Mail/Email";
export {default as Compose} from "../pages/Mail/Compose";
export { default as AddScholar} from "../pages/AddNew/AddScholar";
export { default as AddSupervisor} from "../pages/AddNew/AddSupervisor";
export { default as AddExaminer} from "../pages/AddNew/AddExaminer";
export { default as AddNew} from "../pages/AddNew/AddNew";
export { default as Details} from "../pages/Details/Details";
export { default as Scholar} from "../pages/Details/Scholar/Scholar";
export { default as ScholarDetails} from "../pages/Details/Scholar/ScholarDetails";
export { default as Supervisor} from "../pages/Details/Supervisor";
export { default as DSC} from "../pages/Details/DSC";
export { default as Examiner} from "../pages/Details/Examiner";
export { default as Thesis} from "../pages/Details/Thesis/Thesis";
export { default as Forms} from "../pages/Details/Forms";
export { default as ThesisDetails} from "../pages/Details/Thesis/ThesisDetails";
export { default as Tasks} from "../pages/Tasks/Tasks";
export { default as CE} from "../pages/Tasks/CE";
export { default as PSS} from "../pages/Tasks/PSS";
export { default as RPS} from "../pages/Tasks/RPS";
export { default as UploadForm} from "../pages/Tasks/UploadForm";
export { default as RTC} from "../pages/Tasks/RTC";
export { default as RTE} from "../pages/Tasks/RTE";
export { default as MonthColumnGraph} from "./MonthColumnGraph";
export { default as DepartmentColumnGraph} from "./DepartmentColumnGraph";
export { default as PieGraph} from "./PieGraph";