module.exports = (sequelize,DataTypes)=>{
    const ActivityPlan = sequelize.define("activityPlan",{
        m1:{
            type:DataTypes.ENUM,
            values:["completed","incomplete"],
            defaultValue:"incomplete"
        },
        m1_date:{
            type:DataTypes.DATE
        },
        m1_updated_date:{
            type:DataTypes.DATE
        },
        m2:{
            type:DataTypes.ENUM,
            values:["completed","incomplete"],
            defaultValue:"incomplete"
        },
        m2_date:{
            type:DataTypes.DATE
        },
        m2_updated_date:{
            type:DataTypes.DATE
        },
        m3:{
            type:DataTypes.ENUM,
            values:["completed","incomplete"],
            defaultValue:"incomplete"
        },
        m3_date:{
            type:DataTypes.DATE
        },
        m3_updated_date:{
            type:DataTypes.DATE
        },
        m4:{
            type:DataTypes.ENUM,
            values:["completed","incomplete"],
            defaultValue:"incomplete"
        },
        m4_date:{
            type:DataTypes.DATE
        },
        m4_updated_date:{
            type:DataTypes.DATE
        },
        m5:{
            type:DataTypes.ENUM,
            values:["completed","incomplete"],
            defaultValue:"incomplete"
        },
        m5_date:{
            type:DataTypes.DATE
        },
        m5_updated_date:{
            type:DataTypes.DATE
        },
        m6:{
            type:DataTypes.ENUM,
            values:["completed","incomplete"],
            defaultValue:"incomplete"
        },
        m6_date:{
            type:DataTypes.DATE
        },
        m6_updated_date:{
            type:DataTypes.DATE
        },
        m7:{
            type:DataTypes.ENUM,
            values:["completed","incomplete"],
            defaultValue:"incomplete"
        },
        m7_date:{
            type:DataTypes.DATE
        },
        m7_updated_date:{
            type:DataTypes.DATE
        },
        m8:{
            type:DataTypes.ENUM,
            values:["completed","incomplete"],
            defaultValue:"incomplete"
        },
        m8_date:{
            type:DataTypes.DATE
        },
        m8_updated_date:{
            type:DataTypes.DATE
        },
        m9:{
            type:DataTypes.ENUM,
            values:["completed","incomplete"],
            defaultValue:"incomplete"
        },
        m9_date:{
            type:DataTypes.DATE
        },
        m9_updated_date:{
            type:DataTypes.DATE
        },
        m10:{
            type:DataTypes.ENUM,
            values:["completed","incomplete"],
            defaultValue:"incomplete"
        },
        m10_date:{
            type:DataTypes.DATE
        },
        m10_updated_date:{
            type:DataTypes.DATE
        },
        m11:{
            type:DataTypes.ENUM,
            values:["completed","incomplete"],
            defaultValue:"incomplete"
        },
        m11_date:{
            type:DataTypes.DATE
        },
        m11_updated_date:{
            type:DataTypes.DATE
        },
    });
    return ActivityPlan;
}