module.exports = (sequelize,DataTypes) =>{
    const HonorariumForm = sequelize.define("honorariumForm",{
        name:{
            type:DataTypes.TEXT,
            allowNull:false
        },
        fullAddress:{
            type:DataTypes.TEXT,
            allowNull:false
        },
        thesisDissertation:{
            type:DataTypes.TEXT,
            allowNull:false
        },
        titleOfThesis:{
            type:DataTypes.TEXT,
            allowNull:false
        },
        ExaminedThesisDissertationNumber:{
            type:DataTypes.DOUBLE,
            allowNull:false
        },
        ExaminedThesisDissertationRate:{
            type:DataTypes.DOUBLE,
            allowNull:false
        },
        ExaminedThesisDissertationAmount:{
            type:DataTypes.DOUBLE,
            allowNull:false
        },
        MiscellaneousExpensesNumber:{
            type:DataTypes.DOUBLE,
            allowNull:false
        },
        MiscellaneousExpensesRate:{
            type:DataTypes.DOUBLE,
            allowNull:false
        },
        MiscellaneousExpensesAmount:{
            type:DataTypes.DOUBLE,
            allowNull:false
        },
        grandTotal:{
            type:DataTypes.DOUBLE,
            allowNull:false
        },
        grandTotalInWords:{
            type:DataTypes.TEXT,
            allowNull:false
        },
        nameOfBeneficiary:{
            type:DataTypes.TEXT,
            allowNull:false
        },
        fullAddressOfBeneficiary:{
            type:DataTypes.TEXT,
            allowNull:false
        },
        panCardNumber:{
            type:DataTypes.TEXT,
            allowNull:false
        },
        bankName:{
            type:DataTypes.TEXT,
            allowNull:false
        },
        bankBranchAddress:{
            type:DataTypes.TEXT,
            allowNull:false
        },
        accountNumber:{
            type:DataTypes.TEXT,
            allowNull:false
        },
        ifsc:{
            type:DataTypes.TEXT,
            allowNull:false
        },
        iban:{
            type:DataTypes.TEXT,
            
        },
        aba:{
            type:DataTypes.TEXT,
            
        },
        accountType:{
            type:DataTypes.TEXT,
            allowNull:false
        },
        otherInfo:{
            type:DataTypes.TEXT,
            
        }
    });
    return HonorariumForm;
}